name: issue_context
on:
  issues:
    types: [opened,edited,milestoned]
on: workflow_dispatch
jobs:
  get_issue_context:
    runs-on: ubuntu-latest
    steps:
      - name: print issue context
        run: echo "${{toJson(github)}}"
